#!/usr/bin/env bash
profile=$(tlp-stat -m)
echo $profile
if [[ "$profile" == "performance/AC" ]]; then
    tlpctl power-saver > /dev/null
    new_profile="Power Saver"
elif [[ "$profile" == "power-saver/SAV" ]]; then
    tlpctl balanced > /dev/null
    new_profile="Balanced"
else
    tlpctl performance > /dev/null
    new_profile="Performance"
fi

notify-send "Power Profile Changed" "$new_profile"
