#!/usr/bin/env bash
bat=$(cat /sys/class/power_supply/BAT1/capacity 2>/dev/null)
symbol="󰂎"

if [ "$bat" -gt 80 ]; then
    symbol="󰁹"
elif [ "$bat" -gt 60 ]; then
    symbol="󰂁"
elif [ "$bat" -gt 40 ]; then
    symbol="󰁿"
elif [ "$bat" -gt 20 ]; then
    symbol="󰁼"
fi
echo "$symbol $bat%" 
